secret:
  enabled: true # secret token is enabled
  location: param # location of "secret" parameter (param|header)
  value: 05cb41083cd9778fb0f0f4d33f8388f2 # secret value
  name: api-key # secret parameter name

satis:
  php: /www/server/php/82/bin/php
  bin: ./satis/bin/satis
  config: ./satis.json
  output: ./composer
