secret:
  enabled: true # secret token is enabled
  location: param # location of "secret" parameter (param|header)
  value: veslo # secret value
  name: key # secret parameter name

satis:
  php: /www/server/php/82/bin/php
  bin: ../satis/bin/satis
  config: ../satis.json
  output: ../composer
