secret:
  enabled: true # secret token is enabled
  location: param # location of "secret" parameter (param|header)
  value: 05cb41083cd9778fb0f0f4d33f8388f2 # secret value
  name: api-key # secret parameter name

satis:
  php: /www/server/php/82/bin/php
  bin: /www/wwwroot/composer.phelotto.com/packages/satis/bin/satis
  config: /www/wwwroot/composer.phelotto.com/packages/satis.json
  output: /www/wwwroot/composer.phelotto.com/packages/composer
